-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema puzzle
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `puzzle` ;

-- -----------------------------------------------------
-- Schema puzzle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `puzzle` ;
USE `puzzle` ;

-- -----------------------------------------------------
-- Table `wordsearch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordsearch` ;

CREATE TABLE IF NOT EXISTS `wordsearch` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `number_of_columns` INT(3) NULL,
  `number_of_rows` INT(3) NULL,
  `sentence` TEXT NULL,
  `puzzle` TEXT NULL,
  `solution` TEXT NULL,
  `image` VARCHAR(2083) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS player;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'player' IDENTIFIED BY 'player';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'player';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'player';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `wordsearch`
-- -----------------------------------------------------
START TRANSACTION;
USE `puzzle`;
INSERT INTO `wordsearch` (`id`, `title`, `number_of_columns`, `number_of_rows`, `sentence`, `puzzle`, `solution`, `image`) VALUES (1, 'First Puzzle', 12, 12, 'NOW IS THE TIME FOR ALL GOOD MEN', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'https://placehold.co/400');
INSERT INTO `wordsearch` (`id`, `title`, `number_of_columns`, `number_of_rows`, `sentence`, `puzzle`, `solution`, `image`) VALUES (2, 'Second Puzzle', 6, 6, 'SHELDON PASCIAK', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'https://placehold.co/400');
INSERT INTO `wordsearch` (`id`, `title`, `number_of_columns`, `number_of_rows`, `sentence`, `puzzle`, `solution`, `image`) VALUES (3, 'Third Puzzle', 8, 10, 'ASHLEY BRYAN ACE MARY SHELDON', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'https://placehold.co/400');

COMMIT;

